### ISSUE TITLE
Доработать доступ к пользователям.

### ISSUE THREAD

**Issue by jullitka** [jullitka/sagaart_backend#19]
Мне кажется, в данном проекте свободно просматривать пользователей никто не должен, кроме админов. Ну и каждый может просматривать информацию о себе. Авторов можно, но не пользователей. Сейчас у нас, например, такие настройки, что список пользователей может просматривать то ли админ, то ли залогиненый пользователь, а по id - вообще любой.

**Comment by Fersawas** [comment]
Поправил
