### ISSUE TITLE
Изменить названия эндпоинтов для любимых авторов и произведений. 

### ISSUE THREAD

**Issue by jullitka** [jullitka/sagaart_backend#22]
POST
/api/v1/favorite/{id}/add_favorite/
DELETE
/api/v1/favorite/{id}/add_favorite/
GET
/api/v1/artworks/favorite/
GET
/api/v1/favorite/
Вот эти эндпоинты все про разное, один про картины, другие про художников.  Но что про художников - не понятно. Предлагаю, если уж реализованы эндпоинты таким образом, то поменять название на favorite_artists/ . add_favorite тоже не очень хорошо выглядит с методом delete.

**Comment by Fersawas** [comment]
Поменял на favorite_artists, post и delete запросы идут по эндпоинту favorite_artist/<int:pk>/edit_favorite/
