### ISSUE TITLE
Исправить информацию в выводе избранных произведений

### ISSUE THREAD

**Issue by jullitka** [jullitka/sagaart_backend#26]
/api/v1/artworks/favorite/

в фигме нарисовано, что выводится список работ, в котором отображается: фото работы, имя художника, название работы, цена оригинала, цена постера. 
сейчас при запросе выводится так:
[
    {
        "id": 1,
        "artwork": 3,
        "user": 1
    },
    {
        "id": 2,
        "artwork": 1,
        "user": 1
    }
]

**Comment by mkmmcvrs68** [comment]
Исправил
